version: "3.8"

services:
    backend:
        restart: always
        container_name: backend
        build:
            context: ./backend/
            dockerfile: Dockerfile
        ports:
        - "8000:8000"

    frontend:
        restart: always
        container_name: frontend
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        volumes:
            - .:/frontend/
            - .:/frontend/node_modules
        ports:
        - "3000:3000"
        stdin_open: true
        depends_on:
        - "backend"

